### PR TITLE
Feature/addsNVActivityIndicatorView

### PR DESCRIPTION
**Pull request by cordhernandez**
#182

### CODE REVIEW

**Comment by cordhernandez** [comment]
Can one of the admins verify this patch?

**Comment by SirWellington** [comment]
Looks like there are some conflicts here. Let me know when you have resolved them and I will take a look.

**Comment by cordhernandez** [comment]
I have resolved all conflicts in this branch. Can one of the admins verify? Pleeeease...

**Comment by SirWellington** [comment]
Copy!

**Comment by SirWellington** [comment]
There's a bug. When I first launch the App, the loading indicator is just stuck loading.
img_4887

**Comment by SirWellington** [comment]
Fix the version issue with `NVActivity` and I'll try it again.

**Comment by cordhernandez** [comment]
Sir Wellington can you please run and test this branch on your phone. Thank you.

**Comment by cordhernandez** [comment]
This branch is now bug free. Can an admin please verify this patch?

**Comment by SirWellington** [comment]
On it!

**Comment by SirWellington** [comment]
Works well!!! Looks sweet.

Merge this mother f'kr :8ball:

**Pull request merged**
